theme: minima
title: Caligula
author: David Odolofin
email: odolofindavid@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  David Odolofin. Frontend Engineer.

# social links
twitter_username: Caligularr # DO NOT include the @ character, or else the build will fail!
github_username: David-Odolofin  # DO NOT include the @ character, or else the build will fail!

show_excerpts: false # set to false to remove excerpts on the homepage
